#page title
page_title: Agua y Arena # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6444843272 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: https://apps.apple.com/us/app/agua-y-arena/id6444843272
playstore_link: https://play.google.com/store/apps/details?id=com.aguayarena.aguayarena
presskit_download_link:
  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/agua_arena_icon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Agua y Arena # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Whether you're a local or a visitor, Agua y Arena is the perfect tool for exploring the best beaches Puerto Rico has to offer. So download the app today and start planning your next beach adventure!

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Eduardo Velez and Hector C. Ortiz
your_link: https://www.linkedin.com/company/agua-y-arena-puerto-rico/?viewAsMember=true
your_city: Puerto Rico
email_address: support@aguayarena.com
facebook_username: Agua-y-Arena-Puerto-Rico-112905768319806
instagram_username: aguayarenapr
twitter_username:
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Discover or Explore!
    description: Looking for some inspiration for your next beach adventure in Puerto Rico? Let Agua y Arena be your guide! Our mobile app recommends the top five beaches of the month to help you discover new and exciting places to soak up the sun and surf.
    fontawesome_icon_name: umbrella-beach

  - title: Navigate
    description: With Agua y Arena, you'll have access to detailed information about each beach, including its location, distance from your current location and weather.
    fontawesome_icon_name: map

  - title: Enjoy
    description: So what are you waiting for? Download Agua y Arena today and start exploring the stunning beaches of Puerto Rico!
    fontawesome_icon_name: star

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/aguayarenaheader.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.3

device_color: blue # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
